name: Ejecutar informe.py

on:
  schedule:
    - cron: '0 * * * *'  # Ejecutar cada hora en el minuto 0
  workflow_dispatch:      # Permite correr manualmente

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests pytz

      - name: Ejecutar script informe.py
        run: python repsol-informe/informe.py
